name: Sort awesome lists

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '13 12 * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        awesomelist:
          - url: https://raw.githubusercontent.com/sindresorhus/awesome/main/readme.md
            mdfile: awesome-lists.md
          - url: https://raw.githubusercontent.com/awesome-selfhosted/awesome-selfhosted/master/README.md
            mdfile: awesome-selfhosted.md
          - url: https://raw.githubusercontent.com/alebcay/awesome-shell/blob/master/README.md
            mdfile: awesome-shell.md

    steps:
      - name: Check out this repo
        uses: actions/checkout@v2

      - name: Download previously built sort-awesome-lists executable
        uses: dawidd6/action-download-artifact@v2
        with:
          name: sort-awesome-lists
          workflow: build-sort-awesome-lists.yml

      - name: Sort awesome list
        run: |-
          rm -f "${{ matrix.awesomelist.mdfile }}"
          chmod +x ./sort-awesome-lists
          ./sort-awesome-lists -t "${{ secrets.GITHUB_TOKEN }}" -o "${{ matrix.awesomelist.mdfile }}" "${{ matrix.awesomelist.url }}"

      - name: Commit and push if it changed
        uses: EndBug/add-and-commit@v5
        with:
          author_name: Automated
          author_email: actions@users.noreply.github.com
          message: "Latest ${{ matrix.awesomelist.mdfile }}"
          add: "${{ matrix.awesomelist.mdfile }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
