name: Sort awesome-selfhosted.md

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '13 0,12 * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:

    - name: Check out this repo
      uses: actions/checkout@v2

    - name: Download previously built sort-awesome-lists executable
      uses: dawidd6/action-download-artifact@v2
      with:
        name: sort-awesome-lists
        workflow: sort-awesome-lists.yml

    - name: Sort awesome list
      run: |-
        chmod +x ./sort-awesome-lists
        ./sort-awesome-lists -t "${{ secrets.GITHUB_TOKEN }}" -o "awesome-selfhosted.md" "https://raw.githubusercontent.com/awesome-selfhosted/awesome-selfhosted/master/README.md"

    - name: Commit and push if it changed
      uses: EndBug/add-and-commit@v5
      with:
        author_name: Automated
        author_email: actions@users.noreply.github.com
        message: "Latest awesome-selfhosted.md"
        add: "awesome-selfhosted.md"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
